ripple/ripple-client

- Gruntfile.js
Vault client was overwriting the ripple-lib.
> [FIX] Grant: Change dependency order (RT-3024)

- src/jade/client/navbar.jade
- src/js/controllers/app.js
If account_lines has >200, have a warning in Ripple Trade that
the balances won't be accurate
> [TASK] warning if account_lines has>200 (RT-2732)

- src/js/tabs/send.js
Send: trigger pathfinding if federated address, that requires quoting,
entered after one that not requires
> [FIX] trigger pathfinding on second fed (RT-2644)

- src/js/tabs/send.js
If first found paths are empty - do not report it,
it often founds something on next update
> [TASK] Send: do not report first paths (RT-2176)

- src/js/tabs/send.js
If response from federation request not contains destination
tag, but destionation address requires it - show input field
for destination tag
> [FIX] Send: federation dt check (RT-1327)

- src/js/tabs/exchange.js
If first found paths are empty - do not report it,
it often founds something on next update
> [TASK] Convert: not report first paths (RT-2176)

- src/jade/tabs/history.jade
On an unfunded xrp wallet, on History page,
hide "Loading History" and spinning xrp
> [FIX] hide "Loading history" if unfunded (RT-3070)

- src/jade/tabs/exchange.jade
- src/jade/tabs/send.jade
- src/js/controllers/navbar.js
- src/js/filters/filters.js
- src/js/tabs/balance.js
- src/js/tabs/exchange.js
- src/js/tabs/history.js
- src/js/tabs/send.js
- src/less/ripple/tabs.less
Accidentally closed https://github.com/ripple/ripple-client/pull/2040 and the reopen button is disabled.
Latest text should look like:
You will pay at most
```undefined BTC \pm 1% ```
\+ Ripple network fee:   _Hide network fee_
``` 0.02 XRP ```
> [FEATURE] Send,Exchange: Show Network Fee in confirmation page

- src/jade/tabs/exchange.jade
- src/jade/tabs/send.jade
Always show number, currency and exchange rate on
different lines
> [FIX] Send/Exchange: fix path tiles (RT-3094)

- src/js/filters/filters.js
fix rpamount filter throwing RangeError on very small numbers
problem in ripple.Amount.to_human - it uses Number.toFixed and
does not check arguments. So we must either constrain toFixed
argument to maximum 20 or use some other implementation of toFixed
> [FIX] rpamount error on small numbers (RT-3126)

- src/js/tabs/history.js
rippled doesn't return transaction dates in binary format
> [FIX] Load history in non-binary format (RT-3098)

- src/less/ripple/landing.less
its an alternative solution, I've placed the loader icon in the input visually. so it will not break the columns for input and button.
> [TASK] resend email layout alternate (RT-3103)

- src/js/tabs/balance.js
this uses account_tx to pull your entire transaction history every time your balance updates :/
> [FIX] disable watches for balance trend display

- package.json
- test/karma.conf.js
Until there is a clean solution around this. i.e. to run webpack once
again in karma.
Another way to make this work is to just put coverage in grunt +
istanbul, but then
this reduce the point of using karma in the first place?
> [TASK] Test: Disable coveralls reporter temporarily

- src/jade/tabs/account.jade
- src/jade/tabs/advanced.jade
- src/jade/tabs/security.jade
- src/jade/tabs/settingstrade.jade
> [FIX] Account&Settings: should still show page when rippled is down (RT-3196)

- src/jade/tabs/trust.jade
change error message when trusting unfunded accounts
> [FIX] Trust: better error message (RT-2957)

- src/js/directives/fields.js
- src/js/tabs/send.js
reset last_recipient so when destination tag
is removed from address it will be rechecked
check if match var is defined before use
> [FIX] Send: fix parsing destination tag (RT-3173)

- Gruntfile.js
- package.json
- src/index.html
- test/karma.conf.js
Browser will update cache as needed whenever each assets is updated.
The update is atomic, which means, if a new ripple-client version changes only js files, then the rest of img, css caches will still remain.
For this to work, the expire header in server must be set to never.
> [TASK] Performance: Implement browser cache busting (RT-50)

- src/jade/tabs/send.jade
- src/js/tabs/send.js
If destination account is unfunded, do not allow user to send less than 20 XRP
> [FIX] Send: check destination unfunded (RT-3095)

- Gruntfile.js
- package.json
Actually, css minification reduces the gzipped file by 4 KB.
For this case, the size reduction is
3.2 MB -> 2.7 for uncompressed img/
or
2.6 MB -> 2.5 MB for gzipped file
> [TASK] pagespeed perf: optimize img files

- src/jade/tabs/advanced.jade
https://github.com/ripple/ripple-client/pull/2223 doesn't work because then button is forever disabled when dirty.
> [FIX] Server button: Enable button when form is valid and dirty (RT-3195)

- src/jade/tabs/trust.jade
Use public method to check if value is zero, not private
field _offset.
Internals of Amount class was changed and it does not have
_offset field now.
> [FIX] Trust: use Amount's public api

- src/js/util/jsonrewriter.js
This patch converts fee field in the rewrited transaction from drops to ripple.Amount object
> [FIX] Convert fee in rewrited transaction to ripple.Amount

- src/js/tabs/history.controller.js
It's not needed anymore because fees are converted to Amount objects in jsonrewriter
A little fix related to updated jsonrewriter behaviour
> [FIX] Do not convert fees to Amount in history controller

- src/js/tabs/exchange.controller.js
- src/js/tabs/send.controller.js
use private method for now. this is because rpAmount and other
validators not real validators, but parsers,
and latest angular does not call parsers on $validate.
when rpAmount and others changed to validators this can be changed
back to $validate
> [FIX] fix use of $validate

- src/templates/index.jade
remove inject:css from index.jade
it is not used, but somehow interferes with useref,
but only on ubuntu
> [FIX] fix travis build

- src/js/tabs/btc.controller.js
- src/templates/tabs/btc.jade
Btc2ripple: show appropriate error message when you've
already signed up for btc2ripple using another email address
> [FIX] Btc2ripple: show appropriate error(RT-3334)

- src/js/tabs/trade.controller.js
error object not always have 'engine_result' field in it
> [FIX] trade: fix error checking

- src/js/tabs/trade.controller.js
After placing order, if you switch to another orderbook,
the "Your order is now active." now go away
> [FIX] Trade: reset widgets (RT-3279)

- src/js/tabs/send.controller.js
- src/templates/tabs/send.jade
When sending to a BTC address, show text to indicate that minimum
transaction size is .001 BTC
> [FIX] Send: alert about min btc size (RT-3360)

- src/templates/tabs/settings/navbar.jade
1) Comment out the notifications tab for now (we don't have notifications live yet)
2) Rename "Advanced" to "Network and servers"
3) Rename Gateways to "Gateways and trust lines"
> [FIX] Rename some settings tabs (RT-3381)

- src/templates/tabs/brl.jade
- src/templates/tabs/btc.jade
- src/templates/tabs/eur.jade
- src/templates/tabs/gold.jade
- src/templates/tabs/jpy.jade
- src/templates/tabs/mxn.jade
- src/templates/tabs/sgd.jade
- src/templates/tabs/usd.jade
Do not show "Add" button in custom gateways pages
while Ripple name is loading
> [FIX] Custom gateways: do not show Add (RT-3340)

- src/js/tabs/send.controller.js
- src/templates/tabs/account/public.jade
- src/templates/tabs/contacts.jade
- src/templates/tabs/debug.jade
- src/templates/tabs/send.jade
- src/templates/tabs/trade.jade
In forms that use rpAvailableName or rpDest check not
only for $invalid, but for $pending too.
On send tab better handle changes to recipient address
when form invalidates.
> [FIX] handle change to async validators (RT-3204)

- src/js/tabs/trade.controller.js
Do not convert amount and order values to number
when assigning to input - because chrome and IE shows
big/small numbers in input in scientific notation
use "replace(/,/g, '')" on result of "to_text_full()"
until ripple lib fixed - "to_text_full()" returns
string with group separator
> [FIX] Advanced trade: fix values calculations

- src/js/tabs/trust.controller.js
Fix for Chrome showing very low trust limits in edit
field in e-notation.
> [FIX] Trust: fix e-notation in edit (RT-3250)

- src/js/tabs/send.controller.js
Fix processing of currencies constraints.
When RT is loaded in browser, underscore lib gets replaced
by the lodash by something. And in the old versions of lodash
there was bug in _.intersection method (if argument is just one
array it returned this array). But in recent versions they fixed
this bug, so $scope.update_currency_choices broke.
> [FIX] Send: fix currencies constraints (RT-3393)

- src/js/tabs/trade.controller.js
Advanced Trade: when switching between orderbooks
using the "My Orders" widget check if current pair
is same and do not try to switch in that case.
> [FIX] Trade: "My Orders" orderbooks (RT-3400)

- src/templates/tabs/trade.jade
put back edit order widget model that was changed accidentally
> [FIX] Advanced Trade: fix edit order model

- src/less/ripple/tabs/send.less
- src/templates/tabs/send.jade
> [TASK] Breakpoints in send cut off longer values when in tablet view (RT-2719)

- src/js/tabs/trade.controller.js
- src/templates/tabs/trade.jade
Do not show "Submit another order" screen
after placing an order
> [FIX] Advanced Trade: remove one step (RT-3271)

- src/js/tabs/advanced.controller.js
- src/js/tabs/exchange.controller.js
- src/js/tabs/send.controller.js
- src/templates/tabs/advanced.jade
- src/templates/tabs/exchange.jade
- src/templates/tabs/send.jade
Advanced settings: option to edit the send_max of a Send and Simple Trade
> [FIX] Option to edit the send_max (RT-3205)

- src/js/util/jsonrewriter.js
after selling all IOU balance was zero but negative,
fix that
> [FIX] fix "-0.00" balance (RT-3344)

- src/templates/tabs/btc.jade
fix error message on add btc2ripple confirm
dialog if email is already in use
> [FIX] btc2ripple right error message (RT-3412)

- src/js/directives/directives.directive.js
Use `rp-popup(rp-popup-dismiss-on-esc)` attribute to allow dismissing the popup when the user presses the [Esc] key while the popup is shown.
> [FEATURE] Dismiss locale popup on Esc (RT-3280)

- src/js/util/jsonrewriter.js
- src/templates/tabs/history/effects.jade
In history for orders show price in format
prce: x CURRENCY per CURRENCY (like
"You sold .002046 BTC for 51.15048 XRP (price: 25,000 XRP per BTC)")
> [FIX] History: show price for orders (RT-1385)

- src/js/services/txqueue.service.js
when on unfunded account transaction is getting added
to rpTxQueue, do not ask password - it is not needed
> [FIX] do not ask pass on unfunded (RT-3433)

- deps/gateways.json
add Bluzelle as a CAD currency in the Ripple Trade dropdown
> [TASK] add Bluzelle to dropdown (RT-3493)

- src/js/tabs/login.controller.js
- src/templates/tabs/login.jade
Fix logging in from urls with parameters.
> [FIX] Fix logging in from send urls (RT-3508)

- src/js/services/integration/inboundBridge.service.js
- src/js/tabs/brl.controller.js
- src/js/tabs/btc.controller.js
- src/js/tabs/cad.controller.js
- src/js/tabs/eur.controller.js
- src/js/tabs/exchange.controller.js
- src/js/tabs/gold.controller.js
- src/js/tabs/jpy.controller.js
- src/js/tabs/mxn.controller.js
- src/js/tabs/send.controller.js
- src/js/tabs/sgd.controller.js
- src/js/tabs/trade.controller.js
- src/js/tabs/trust.controller.js
- src/js/tabs/usd.controller.js
add mime type (text/plain) to transaction.addMemo calls
as second parameter
> [FIX] fix calls to transaction.addMemo (RT-3497)

- src/js/directives/validators.directive.js
Allow only canonical (staring with 'r') form of ripple addresses
to be used on send tab.
> [FIX] Send: check address (RT-3510)
