src/jade/tabs/trade.jade
src/js/directives/formatters.js
src/less/ripple/content.less
src/less/ripple/tabs.less

[TASK] Change orderbook styling (RT-3026)

---

src/js/util/jsonrewriter.js

Do not show fee in CSV if fee wasn't applied to our account

[FIX] History: remove fee if none (RT-2521)

---

test/e2e/utils/forms.js

updates e2e/utils/forms.js exports.logout() - changing selectors to jquery style selectors and fixing logout

[TEST] e2e: fixes logout and changes selectors to jquery

---

src/js/controllers/navbar.js
src/js/services/network.js

When websockets connection is down, wait 2 seconds before
showing offline message, in case it goes up again in that time

[TASK] Wait 2sec before showing offline (RT-3029)

---

src/jade/tabs/login.jade
src/jade/tabs/login/form.jade
src/jade/tabs/privacypolicy.jade
src/jade/tabs/tou.jade
src/less/ripple/landing.less

[FIX] ToS/Privacy policy page fix, error message, 2fa margin

---

src/less/ripple/tabs.less

make it same on windows and on mac

[FIX] Fix aligment of check box (RT-3001)

---

.gitignore
Gruntfile.js
bower.json
src/jade/tabs/settingstrade.jade
src/js/entry/web.js
src/js/tabs/settingstrade.js
src/less/ripple/sortable.less
src/less/ripple/tabs.less
src/less/ripple/web.less

Edit state for trade pairs: allow ability to move pairs around

[TASK] Ability to move trade pairs (RT-2875)

---

src/js/tabs/exchange.js
src/js/tabs/trade.js

Send "Convert" order results to mixpanel - including
sum amount
Also sums amount in 'Trade order result' event

[TASK] track "Convert" orders (RT-2910)

---

src/jade/tabs/send.jade
src/js/services/federation.js
src/js/tabs/send.js
src/less/ripple/forms.less
src/less/ripple/tabs.less

Send: when bridge are down, show error "could not contact bridge"
instead of "This address is not Ripple-enabled."

[TASK] better error when bridge down (RT-2147)

---

src/jade/tabs/send.jade
src/js/tabs/send.js
src/less/ripple/tabs.less

Show 'Set btc2ripple.com bridge' if bridge is not that 
and there is error trying to send to btc address
this pr based on https://github.com/ripple/ripple-client/pull/2084 because it changes same code

[TASK] Send: 'set btc2ripple' bridge (RT-2999)

---

src/jade/tabs/trust.jade
src/js/directives/validators.js

Allow to set trust line limit to zero

[TASK] Trust: allow zero limit (RT-3003)

---

src/js/tabs/send.js

Send: trigger pathfinding for adresses without name

[FIX] Send to adresses with no name

---

src/js/directives/fields.js

rpCombobox - on Enter, do not choose single suggested choice
if dropdown is not visible

[FIX] Send: fix on Enter behaviour  (RT-2624)

---

src/js/tabs/send.js

save flag to contact to not check account again
if contact is funded and do not require destination tag

[TASk] Skip checking contacts account (RT-1330)

---

Gruntfile.js
src/jade/tabs/advanced.jade
src/js/directives/validators.js
src/js/entry/web.js
src/js/services/network.js
src/js/services/txqueue.js
src/js/tabs/eur.js
src/js/tabs/trade.js

Note: With this, now it is possible to have a more granular error
message.
When:
1. The string entered is not even a valid hostname.
2. The string entered is valid, i.e. the server exists / is up, but it
is not a rippled server.
Currently both errors are combined into one.

[TASK] Advanced: Actually ping server to check validity (RT-2287)

---

src/js/tabs/trade.js

Take into account currency of "Amount to Buy" when calculating "Order Value"

[FIX] Trade: take into account currency (RT-3054)

---

src/jade/tabs/settingstrade.jade

Trade settings tab: show "no pairs" messages
if there no pairs to edit

[TASK] No pairs message (RT-2992)

---

src/jade/tabs/exchange.jade
src/jade/tabs/send.jade
src/js/tabs/exchange.js
src/js/tabs/send.js

set maximum send and conversion threshold to 0.1%

[TASK] set send threshold to 0.1% (RT-2205)

---

src/js/tabs/send.js

Search for paths even if destination doesn't exist - so
accaunt can be funded using non-XRP

[TASk] Send: fund in non-XRP (RT-1225)

---

.gitignore
README.md
package.json
src/js/tabs/account.js
test/karma.conf.js

Wait until it shows up in http://direct.coveralls.io/r/ripple/

[TASK] Test: Add Travis badge and code coverage

---

src/jade/tabs/trust.jade
src/js/directives/accountExists.js
src/js/entry/web.js

Do not allow people to trust unfunded accounts

[TASK] Do not trust unfunded accounts (RT-2957)

---

src/jade/strings/myOrders.jade
src/jade/tabs/trade.jade
src/jade/tabs/widgets/orders.jade
src/js/controllers/app.js
src/js/directives/directives.js
src/js/tabs/balance.js
src/js/tabs/trade.js
src/less/ripple/widgets.less

Use standart combobox for My Orders mobile view sort dropdown

[FIX] My Orders: use standart combobox (RT-2963)

---

src/jade/tabs/history.jade
src/jade/tabs/trust.jade
src/js/config-example.js
src/js/entry/web.js
src/js/services/id.js
src/js/tabs/advanced.js
src/js/tabs/history.js
src/js/tabs/trust.js

Store advanced trustline settings in the user blob,
not browser's local storage

[TASK] Store trustline settings in blob (RT-2862)

---

src/jade/tabs/banner/unfunded.jade
src/jade/tabs/trust.jade

Started using your client for the first time and noticed that you have some expired links in it. Just updated them to hopefully point to the right place.

Updated expired link.

---

src/jade/tabs/trade.jade
src/jade/tabs/widgets/orders.jade
src/js/directives/directives.js
src/less/ripple/widgets.less

My Orders: Change sorting arrows to match size
and shape of other arrows on overview page

[TASK] My Orders: Change sorting arrows (RT-2950)

---

src/js/tabs/exchange.js
src/js/tabs/send.js

Re-apply Orzfly's Send/Convert pathfinding changes

[TASK] Send/Convert pathfinding changes (RT-2638)

---

src/jade/tabs/contacts.jade
src/jade/tabs/trade.jade
src/jade/tabs/widgets/orders.jade
src/js/directives/directives.js
src/js/filters/filters.js
src/js/tabs/contacts.js
src/less/ripple/tabs.less
test/e2e/pages/tradePage.js

[TASK] Contacts: Add name/address sort & contact search (RT-1752)

---

src/jade/tabs/trade.jade
src/less/ripple/tabs.less
src/less/ripple/widgets.less

[TASK] My orders: fix buttons styles (RT-3049)

---

src/js/services/id.js
src/js/tabs/login.js

I did redirection fixes on login

[TASK] Landing: Show register on first visit (RT-2982)

---

src/js/tabs/register.js

Register/Resend email: if user cancelled password request
prompt, just show current resend form, instead of blank

[FIX] Register/Resend: fix blank state  (RT-3105)

---

src/jade/tabs/contacts.jade

[FIX] Contacts: Align notifications and content (RT-3124)

---

src/jade/tabs/trade.jade
src/js/tabs/trade.js

In price ticker show bid/ask prices from price field
(do not try to calculate them)

[FIX] Advanced trade: fix price ticker (RT-3136)

---

src/jade/tabs/security.jade
src/less/ripple/tabs.less

[TASK] Change color and set lowercase of "send via sms" (RT-3052)

---

src/jade/client/index.jade

[TASK] Rename mobile menu Convert and Trade items (RT-3131)

---

src/jade/tabs/register.jade

[TASK] Secret Key input type password (RT-3109)

---

src/jade/tabs/login/form.jade

[TASK] login tab: 2FA buttons alignments (RT-3120)

---

src/jade/client/navbar.jade
src/less/ripple/content.less
src/less/ripple/layout.less

[TASK] Account recovery success message standard styles (RT-3108)

---

src/index.html

Enable caching for js/ripple-client-{lang}.js

[TASK] Client: Enable AJAX caching

---

src/jade/tabs/advanced.jade
src/js/directives/validators.js

Form's default validity is false unless a websocket connection has
been made.

[FIX] Advanced: Disable save button while checking validity (RT-3195)

---

src/jade/tabs/send.jade
src/js/services/keychain.js
src/js/tabs/login.js
src/js/tabs/send.js

periodically check password fields for changes
to work with password managers (such as Entropass)
that change input value but do not raise change event

[FIX] work with password managers (RT-2861)

---

src/jade/tabs/exchange.jade
src/jade/tabs/send.jade
src/js/filters/filters.js

And also set IOU precision limit to 15 to be consistent with the wiki

[TASK] Send,Exchange: Add exchange rate (RT-3082)

---

src/jade/messages/sendconvert/localerror.jade
src/jade/popup/unlock.jade
src/jade/tabs/account/public.jade
src/js/services/keychain.js
src/js/tabs/account.js

better error messages if auth server is unreachable

[FIX] better error messages (RT-2480)

---

src/js/controllers/app.js
src/js/controllers/navbar.js
src/js/services/id.js
src/js/services/integration/inboundBridge.js
src/js/services/keychain.js
src/js/services/txqueue.js
src/js/tabs/_usd.js
src/js/tabs/advanced.js
src/js/tabs/kyc.js
src/js/tabs/security.js
src/js/tabs/settingstrade.js
src/js/tabs/trade.js
src/js/tabs/twofa.js
src/js/util/settings.js
test/unit/util/settingsSpec.js

move all the client specific settings from root scope to clients.rippletrade
setting moved
persistUnlock
lastSeenTxDate
trade_currency_pairs
txQueue

[TASK] move settings to rippletradecom (RT-2990)

---

.travis.yml
Gruntfile.js
test/selenium/interpreter_config.json
test/selenium/tests/LoginRT.json
test/selenium/tests/openRT.json

configure travis to run e2e tests
on Sauce Labs servers

[TEST] run tests on Sauce Labs

---

src/js/tabs/register.js

fix email verification link if logged
into a different account

[FIX] fix email verification link (RT-3202)

---

.travis.yml
test/selenium/tests/LoginRT.json
test/travis/config-travis.js
test/travis/nginx.conf
test/travis/ripple-travis.txt

added websockets proxy because Sauce Labs
does not allow outgoing websockets connections

[TEST] run e2e tests on Sauce Labs

---

src/jade/tabs/usd.jade

[TASK] Usd: Drop cash option in deposit (RT-3218)

---

src/js/services/id.js
src/js/tabs/register.js

Sign-up: resend email without requiring unlock

[FIX] Resend email without unlock (RT-3104)

---

src/jade/client/navbar.jade
src/js/controllers/navbar.js
src/less/ripple/content.less
src/less/ripple/layout.less
test/unit/controllers/navbarControllerSpec.js

For now it only shows green/gray for online/offline. At some point we'll make it smarter. 
This also removes the annoying black offline popup.

[TASK] Navbar: Add a server status icon

---

src/js/controllers/app.js
src/js/tabs/trust.js

Logged in user doesn't care about the lines where he/she's in a default state, limits are zero but the counterparty is not in a default state (has a non default flag)

[TASK] Trust: Don't show insignificant trustlines

---

src/jade/tabs/account/public.jade
src/jade/tabs/advanced.jade
src/jade/tabs/contacts.jade
src/jade/tabs/debug.jade
src/jade/tabs/fund.jade
src/jade/tabs/register.jade
src/jade/tabs/send.jade
src/jade/tabs/trust.jade
src/js/directives/directives.directive.js
src/js/directives/validators.directive.js
src/js/validators/rpWebsocket.directive.js

Side effect: simplify rpSpinner

[TASK] Rewrite server-side validators in $asyncValidators (RT-3217)

---

src/js/services/id.service.js
src/js/tabs/balance.controller.js

Update "Net Worth" drop down when names
of currencies issuers are resolved

[FIX] Update "Net Worth" drop down  (RT-3091)

---

src/js/entry/web.js
src/js/tabs/exchange.controller.js
test/unit/tabs/exchange.controller.spec.js

Re-validate input when currency changed,
and do not start pathfinding if input
is not valid

[FIX] Send: better show input errors (RT-2975)

---

src/js/services/id.service.js
src/js/tabs/advanced.controller.js
src/js/util/settings.js

Advanced: Save server settings in the blobvault

[TASK] Save server settings in blob (RT-3224)

---

src/js/tabs/exchange.controller.js
src/js/tabs/send.controller.js

use Amount.from_human instead of Amount.from_json
to create native amount value from string

[FIX] fix Amount use

---

src/js/directives/validators.directive.js

return rejected promise to
indicate that value is invalid

[FIX] fix rpDest

---

src/js/directives/addressPopover.directive.js

[TASK] Trust UI: popover shows -0.00 (RT-3267)

---

src/jade/client/navbar.jade
src/js/controllers/app.controller.js
src/js/controllers/navbar.controller.js

This should be independent of auth connection status

[FIX] serverStatus: update fee on net connected/disconnected (RT-3323)

---

src/js/controllers/app.controller.js
src/js/tabs/history.controller.js

stop history loading spinner on unfunded accounts

[FIX] stop history loading spinner (RT-3070)

---

test/selenium/tests-private/CustomGatewaysBRL.json
test/selenium/tests-private/CustomGatewaysEUR.json
test/selenium/tests-private/CustomGatewaysJPY.json
test/selenium/tests-private/CustomGatewaysMXN.json
test/selenium/tests-private/CustomGatewaysSGD.json
test/selenium/tests-private/CustomGatewaysUSD.json
test/selenium/tests-private/CustomGatewaysXAU.json

e2e tests for AUD, BRL, EUR, JPY, MXN, NZD, SGD,
USD and XAU gateways.

[TEST] e2e tests for custom gateways (RT-3331)

---

test/selenium/tests-private/SendBTC.json
test/selenium/tests-private/SendFederation.json
test/selenium/tests-private/SendLimits.json
test/selenium/tests-private/SendUSD.json

try to send BTC
try to send USD
try to send to federation address
try to send invalid amount

[TEST] e2e tests for send tab

---

test/selenium/tests-private/TradeNonXRP.json
test/selenium/tests-private/TradePairsAddress.json
test/selenium/tests-private/TradePairsName.json
test/selenium/tests-private/TradeXRP.json

e2e tests for placing orders and trade pairs:
Add/remove a custom trade pair using full Ripple addresses.
Add/remove a custom trade pair using Ripple names.
Place/remove order to XRP/USD.Bitstamp orderbook.
Place/remove order to USD.Bitstamp/USD.Snapswap orderbook.

[TEST] e2e tests for placing orders (RT-3327)

---

src/js/entry/web.js

make lang global var be explicitly global
(after latest build system change it stopped being global)

[FIX] fix lang global var

---

src/js/tabs/trade.controller.js

Clean price ticker when trade pair changes,
so user do not see data from previous pair
while new data loads.

[FIX] Trade: clean ticker on change (RT-3336)

---

.travis.yml
test/selenium/tests-private/SendLimits.json
test/selenium/tests-private/SendUSD.json
test/selenium/tests-private/TradeNonXRP.json
test/selenium/tests-private/TradePairsName.json

make them work in chrome and safari
"SendUSD" test use second testing account

[TEST] fix e2e tests

---

src/js/tabs/send.controller.js

fix sending when "Send confirmation settings" set to Hide

[FIX] fix sending without confirmation (RT-3337)

---

gulpfile.js
src/templates/index.jade

remove whitespaces and newlines from version string in dev version
(that version string goes to into transaction as memo field and
transaction gets reject because of invalid characters)

[FIX] fix version string inside html

---

src/templates/tabs/btc.jade

Show btc2ripple module as loading while it is loading

[FIX] BTC: Show "loading" (RT-3340)

---

src/js/tabs/trade.controller.js

Trade: "modify order" load html using templateCache instead of require jade

[FIX] Trade: "modify order" load html (RT-3359)

---

src/js/services/keychain.service.js

keychain: use the html template using the angular $templateRequest instead of jade

[FIX] keychain: use the $templateRequest(RT-3358)

---

src/js/controllers/app.controller.js

load myOrders.html instead of myOrders.jade using angular templateCache

[FIX] app.controller: load myOrders.html(RT-3356)

---

src/js/services/id.service.js
src/js/tabs/exchange.controller.js
src/js/tabs/trade.controller.js

Save last trade page user went to (Simple or Advanced)
to user blob.

[FIX] Save last trade page (RT-3259)

---

src/js/tabs/contacts.controller.js
src/templates/tabs/contacts.jade

For creating/deleting/updating contacts use standard
notifications mechanism (that notifications dissapear
after timeout)

[FIX]Contacts: use standard notification(RT-2915)

---

src/js/directives/formatters.directive.js
src/templates/tabs/contacts.jade

Show Ripple name for contact instead of Ripple address

[FIX] Contacts: show ripple names (RT-3125)

---

src/js/tabs/trade.controller.js

do not reload orderbook when starting editing order
if orders pair match current book's pair

[FIX] My orders: do not reload orderbook(RT-3364)

---

src/js/directives/addressPopover.directive.js

addressPopover: load addresspopover.html instead of the jade file
using $templateRequest

[FIX] addressPopover: use $templateRequest (RT-3357)

---

src/templates/tabs/brl.jade
test/selenium/tests-private/CustomGatewaysBRL.json

add id to "Add Rippex" button on #brl tab and use it in e2e test

[TEST] BRL e2e test fix

---

test/selenium/tests-private/TradeNonXRP.json

[TEST] e2e TradeNonXRP test fix

---

src/js/directives/fields.directive.js
src/templates/tabs/history.jade

History: force "to" date to be biger than "from"

[FIX] History: force "to" date (RT-3374)

---

src/js/tabs/settingsgateway.controller.js
src/templates/tabs/settingsgateway.jade

Add loading icon and notifications when changing defaultRipple settings

[FIX] Editing defaultRipple settings (RT-3398)

---

src/js/tabs/send.controller.js
src/templates/index.jade

Include underscore after other libs to prevent lodash overwriting '_'
variable which is intended for underscore

[FIX] Prevent lodash overwriting underscore RT-3407

---

src/js/services/id.service.js
src/js/tabs/settingstrade.controller.js
src/js/tabs/trade.controller.js
src/templates/tabs/settingstrade.jade

Fix editing trade pairs order.
Clean trade pairs list - remove $$hashKey, remove duplicates.
Check trade pair before adding.

[FIX] Trade: fix trade pairs order edit (RT-3343)

---

src/templates/tabs/trade.jade

Orderbook: Show loading instead of "no bids"

[FIX] Trade: Show loading for orderbooks(RT-3402)

---

src/js/directives/accountExists.directive.js
src/js/directives/validators.directive.js
src/templates/tabs/trust.jade

Numeric code for error was changed in rippled.
Instead numeric, check error's string tag - hopefully
it will not change in future.

[FIX] Trust: fix not to trust unfunded (RT-2957)

---

src/templates/tabs/widgets/balances.jade

Show 4 decimal places on XRP in balance widget

[FIX] Balance widget: 4 decimal places (RT-3390)

---

src/js/tabs/trade.controller.js
src/templates/tabs/trade.jade

Show only Available XRP.
Do not allow to place an order if Available XRP <=0

[FIX] Trade: show only Available XRP (RT-3389)

---

src/js/entry/web.js
src/js/tabs/cad.controller.js
src/less/ripple/tabs/gateways.less
src/templates/tabs/cad.jade
src/templates/tabs/fund/menu.jade

Add Bluzelle as a featured gateway for CAD

[FEATURE] Add Bluzelle gateway for CAD (RT-3441)

---

src/js/tabs/trade.controller.js
src/less/ripple/tabs/trade.less
src/templates/tabs/trade.jade

Advanced Trade: highlight new/updated orders
with green/red color.

[FEATURE] Highlight new/changed orders (RT-3278)

---

src/js/entry/web.js
src/js/util/jsonrewriter.js
test/unit/util/jsonRewriterSpec.js

fix how incoming trust line shown while logged in

[FIX] incoming trust line fix (RT-3392)

---

bower.json
src/js/services/id.service.js
src/js/tabs/settingstrade.controller.js

Fix trade pairs order edit.
Update ng-sortable to latest version.

[FIX] Fix trade pairs edit (RT-3343)

---

src/js/util/jsonrewriter.js

take into account case when there is no transaction in RippleState node

[FIX] fix json rewriter

---

src/js/controllers/app.controller.js
src/js/entry/web.js
src/js/services/id.service.js
src/js/tabs/logout.controller.js
src/less/ripple/tabs/security.less
src/templates/tabs/logout.jade
src/templates/tabs/security.jade

https://RT.URL/#/logout?redirect_to=URL logs out user
from RT and RTB and redirects back to the mentioned URL

[FEAT] Logout: Logout URL for IDS autologout

---

src/js/services/id.service.js
src/js/tabs/send.controller.js

Do not add tilde to ripple address if
there is no ripple name for that address.

[FIX] Send: Do not add tilde (RT-3484)

---

src/js/tabs/login.controller.js
src/js/tabs/send.controller.js
src/templates/tabs/send.jade

Disable federation for non KYCd people
This commit is not tested with real backend because required changes to it still not deployed into production.

[TASK] Disable federation for non KYCd (RT-3488)

---

src/js/tabs/exchange.controller.js
src/js/tabs/send.controller.js
src/templates/messages/sendconvert/localerror.jade

Show right message when user entered wrong password.

[FIX] Send: wrong password message (RT-3491)

---

deps/gateways.json
src/js/tabs/eur.controller.js
src/js/tabs/usd.controller.js
src/templates/tabs/eur.jade
src/templates/tabs/usd.jade

Add GateHub gateway to the Gateways list

[TASK] Add GateHub gateway (RT-3486)

---

deps/gateways.json
src/templates/client/layout.jade

Remove coinex gateway logo from homepage and from list of gateways.

[TASK] Remove coinex gateway (RT-3485)

---

src/less/ripple/layout.less

Show horizontal scrollbar on small devices, if needed

[FIX] Horizontal scroll on small devices(RT-3495)

---

src/less/ripple/tabs/trade.less

Stack trade widgets one on top of another on small displays

[FIX] Trade advanced on mobile (RT-3525)

---

src/templates/tabs/exchange.jade

Allow to input number on Trade Simple page in mobile layout

[FIX] Trade simple on mobile (RT-3524)

---

src/js/directives/fields.directive.js

do not call setCompletions twice

[FIX] fix rpCombobox

---

src/js/tabs/history.controller.js

Export exchange transactions into csv

[FEATURE] Export exchange transactions (RT-3466)
